version: '2'
# starts 4 docker containers running minio server instances. Each minio server's web interface will be accessible on the host at port 9001 through 9004.
services:
  minio1:
    image: minio/minio
    volumes:
      - data1:/data
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: 5J9Q0SRX2HJR2E5HCE8B
      MINIO_SECRET_KEY: cFHCDKL73Dzc9fgV6Lh7Bb/8tmTztKPr3jp9pG3D
    networks:
      - minio-net
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data 
    
  minio2:
    image: minio/minio
    volumes:
      - data2:/data
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: 5J9Q0SRX2HJR2E5HCE8B
      MINIO_SECRET_KEY: cFHCDKL73Dzc9fgV6Lh7Bb/8tmTztKPr3jp9pG3D
    networks:
      - minio-net
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data 
    
  minio3:
    image: minio/minio
    volumes:
      - data3:/data
    ports:
      - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: 5J9Q0SRX2HJR2E5HCE8B
      MINIO_SECRET_KEY: cFHCDKL73Dzc9fgV6Lh7Bb/8tmTztKPr3jp9pG3D
    networks:
      - minio-net
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data 
    
  minio4:
    image: minio/minio
    volumes:
      - data4:/data
    ports:
      - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: 5J9Q0SRX2HJR2E5HCE8B
      MINIO_SECRET_KEY: cFHCDKL73Dzc9fgV6Lh7Bb/8tmTztKPr3jp9pG3D
    networks:
      - minio-net
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data 

  minio_nginx:
    image: nginx:1.13.9-alpine
    restart: always
    ports:
      - 9000:80/tcp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./minio.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - minio1
      - minio2
      - minio3
      - minio4
    networks:
      - minio-net

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1:
  data2:
  data3:
  data4:

networks:
  minio-net:
    driver: bridge

